METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  #clip_grad: 5

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 80
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 80
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500


  model_args:
    num_nodes: 358
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 0
    adaptive_embedding_dim: 12
    kernel_size: [1]
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.5

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [15, 30, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    kernel_size: [1]
    adaptive_embedding_dim: 12
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.05

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [15, 35, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    
    adaptive_embedding_dim: 80
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500


  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 12
    kernel_size: [1]
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.35

SD:
  num_nodes: 716
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 716
    in_steps: 12
    out_steps: 12
    steps_per_day: 96
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 12
    kernel_size: [12]
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.3

  
GBA:
  num_nodes: 2352
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 2352
    in_steps: 12
    out_steps: 12
    steps_per_day: 96
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 12
    kernel_size: [12]
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.0

GLA:
  num_nodes: 3834
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2500

  model_args:
    num_nodes: 3834
    in_steps: 12
    out_steps: 12
    steps_per_day: 96
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 12
    kernel_size: [12]
    
    num_heads: 4
    num_layers: 3
    dropout: 0.1
    dropout_a: 0.2

